nextcloud/ocsms

- lib/countrycodes.php
Hi, please add country code for Iran +98
thanks
> Add Iran (+98) to contrycode

- lib/countrycodes.php
Here is a link to an authoritative source for reference: http://www.australia.gov.au/about-australia/our-country/telephone-country-and-area-codes
> Added Australia's country code

- img/app.svg
See https://github.com/nerzhul/ownCloud-SMS-App/pull/83
> New icon for server application

- README.md
> no need for issue template

- js/public/app.js
> Reset message count and only add new messages on refresh.

- css/style.css
> Fix left navigation layout

- css/style.css
> Style messages more modern

- css/style.css
- Invert header colors for better readability
- Use `flex-box` in header
- Increase size of header image and adjust layout
- Change font-color of sent date to grey because it is not as important as the content (with darker grey on hover)
- Use same opacity of delete button as in contacts app (hover: opacity: 1)
- Remove some dead css-code
Sorry for not providing a screenshot (there's too much private data i would have to hide).
> Some style changes (header, colors, ...)

- db/smsmapper.php
Your patch for https://github.com/nerzhul/ocsms/issues/140 didn't fix issue for me but this change i made fix it. It makes use of the "limit" prepare function.
> Fix SyntaxErrorException on select limit

- controller/smscontroller.php
- js/public/app.js
- lib/contactcache.php
- templates/main.php
> Set contact colours on uids

- l10n/.tx/config
> provide transifex config

- appinfo/app.php
> Use non-deprecated call to add navigation entry

- README.md
- appinfo/app.php
- appinfo/ocsmsapp.php
- appinfo/routes.php
- controller/apicontroller.php
- controller/settingscontroller.php
- controller/smscontroller.php
- db/configmapper.php
- db/conversationstatemapper.php
- db/sms.php
- db/smsmapper.php
- issue_template.md
- js/public/app.js
- lib/contactcache.php
- lib/countrycodes.php
- lib/migration/fixconversationreadstates.php
- lib/phonenumberformatter.php
- tests/autoloader.php
Sorry forgot to mark previous PR as WIP 😁 Please squash the PR to one commit ^^
> Corrected missing Nc branding

- db/conversationstatemapper.php
- db/smsmapper.php
cc @nerzhul
Will be dropped in 14 😉 
See https://github.com/nextcloud/server/issues/7827
> Use DB transaction methods of the DB connection

- js/devel/legacy.js
Also add a fallback CSS class
Fixes #238
> Fix the display of the SMS bubbles

- css/style.css
This makes the caller header info in to a sticky div so it is always visible as the user scrolls through messages.
> Convert the caller info to a sticky header

- css/style.css
> Set the settings container to the contacts width.

- templates/main.php
If there is no avatar icon to match the contacts list style.
> Display the contacts first initial in the app header.

- templates/main.php
Add translation support for the strings in the main template as well as clean up some of the text for better readability.
> Minor text cleanups and translation support.

- css/style.css
- templates/main.php
So that the template items aren't displayed until they are required.
> Add ng-cloak support.

- appinfo/routes.php
- controller/smscontroller.php
- css/style.css
- db/smsmapper.php
- js/devel/app.js
- js/devel/contactlist.js
- js/devel/settings.js
- templates/main.php
> Add query + routes to drop all user messages

- db/conversationstatemapper.php
- db/smsmapper.php
I didn't get around to them all, sorry. Just enough to browse through some conversations without logging errors. Hopefully this goes some way to helping with #266.
> Convert some queries to QueryBuilder.

- templates/main.php
Correction of the description buttons of the message removal request
> Update[2] main.php

- l10n/de.js
- l10n/de.json
- l10n/de_DE.js
- l10n/de_DE.json
- l10n/es.js
- l10n/es.json
- l10n/fr.js
- l10n/fr.json
- l10n/gl.js
- l10n/gl.json
- l10n/hu.js
- l10n/hu.json
- l10n/pl.js
- l10n/pl.json
- l10n/tr.js
- l10n/tr.json
Removed unclear string.
Fixed #285 
Signed-off-by: Mark Ziegler <mark.ziegler@rakekniven.de>
> Rakekniven patch 1

- db/smsmapper.php
Attempt to fix https://github.com/nextcloud/ocsms/issues/282
Works locally for me, but not sure about potential wider implications.
> Fix for conversations of contacts not showing any messages

- css/style.css
fix https://github.com/nextcloud/ocsms/issues/297
> Fix unreadable messages with dark theme
